name: oncoscape
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch>=2.2
  - torchvision
  - pandas
  - numpy<2
  - scipy
  - pyarrow
  - pyyaml
  - anndata>=0.12,<0.13
  - h5py
  - pillow
  - sphinx
  - zarr<3
  - pip:
      - timm
      - openslide-python
      - scvi-tools
      - cell2location
